<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CRMAccount</name>
   <tag></tag>
   <elementGuidId>24620c79-b12e-49ea-abbc-ccdb5995579a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#account</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='account']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>873a74d4-9123-4ad0-978b-2b42e1818d54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f9fab843-3be4-4465-bea9-51e303ee5607</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>邮箱</value>
      <webElementGuid>fe174ad8-4d4f-4b62-a5fd-ac8d13ea0807</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>account</value>
      <webElementGuid>31e89dd4-2f70-475f-b37c-5865c7660caa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-__meta</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>044fb9c3-0c51-46a6-9914-d99e3544bde9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input ant-input-lg</value>
      <webElementGuid>32dfd6ab-0470-4cfe-bfec-1a5a59dd40dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;account&quot;)</value>
      <webElementGuid>b505cc27-fa6c-4e17-99fb-0b56441df992</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='account']</value>
      <webElementGuid>8c56a925-0cff-49d3-977f-bd080f6c22f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/div/form/div[2]/div[2]/div/span/input</value>
      <webElementGuid>191027b0-ffd9-46b3-a3fa-e795cea5601d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>d8d4a7e5-866e-4f15-90f2-25fb1b47b3f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = '邮箱' and @id = 'account']</value>
      <webElementGuid>5bcf72c9-d1d5-4bd7-8fbd-9a1cedc3b1c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
