<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>MT4Account</name>
   <tag></tag>
   <elementGuidId>dbae4cc6-ecab-49dd-8d2b-b1b2798dd205</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.ant-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6aaf0f5f-03ef-4448-aa63-90504b67abcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>58cc1e55-d406-44f2-8f2d-3be3413d3e54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>搜索关键字</value>
      <webElementGuid>d6c2c21c-f203-47ec-91d7-dfc8ddd478cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input</value>
      <webElementGuid>2a1214cb-0f7a-440c-b367-3c94eaf7c207</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;gx-layout&quot;]/div[@class=&quot;gx-layout-main&quot;]/div[@class=&quot;gx-layout-container&quot;]/div[@class=&quot;gx-layout-content&quot;]/div[1]/div[1]/div[@class=&quot;ant-row gx-table-toolbar&quot;]/div[1]/div[@class=&quot;pull-right gx-margin-left-5&quot;]/span[@class=&quot;ant-input-wrapper ant-input-group&quot;]/input[@class=&quot;ant-input&quot;]</value>
      <webElementGuid>6bcbc167-a923-4d05-a290-6d4b119ede44</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='text']</value>
      <webElementGuid>1fd47bc8-5fba-4f1c-b049-0f4ef29bdc9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/div[2]/div[2]/div/div/div/div/div/div[7]/span/input</value>
      <webElementGuid>5e2abd20-0d5f-40ba-ac54-26f67c6b9784</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/span/input</value>
      <webElementGuid>ded769c2-2a36-4455-a2a6-8af5bc4e398c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = '搜索关键字']</value>
      <webElementGuid>965faf20-65f5-4fde-adab-03c870c0cc56</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
