<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>noReason_SIT</name>
   <tag></tag>
   <elementGuidId>061865e2-9da3-42e7-b082-1065f22c2445</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.ant-select-dropdown-menu-item-active.ant-select-dropdown-menu-item</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[4]/div/div/div/ul/li</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'ant-select-dropdown-menu-item-active ant-select-dropdown-menu-item' and (text() = '无原因' or . = '无原因')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>6bba6507-7937-4a5c-b579-48eb91e4f951</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>unselectable</value>
      <webElementGuid>612a9677-f14a-4f28-be45-ccdd599c0c97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-select-dropdown-menu-item-active ant-select-dropdown-menu-item</value>
      <webElementGuid>bd88d8a0-bf50-4507-9e87-2b85162f56dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>33ab74f5-f79f-4ebb-abef-8464af012c3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7ccd364d-3923-4355-bc13-3bd88c6b4c80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>无原因</value>
      <webElementGuid>816e73c2-aca1-4805-8f41-9b5fac27db29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[4]/div[1]/div[@class=&quot;ant-select-dropdown ant-select-dropdown--single ant-select-dropdown-placement-bottomLeft&quot;]/div[1]/ul[@class=&quot;ant-select-dropdown-menu ant-select-dropdown-menu-vertical  ant-select-dropdown-menu-root&quot;]/li[@class=&quot;ant-select-dropdown-menu-item-active ant-select-dropdown-menu-item&quot;]</value>
      <webElementGuid>648bf5c4-1bca-4e97-b0dd-d02d242da597</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/ul/li</value>
      <webElementGuid>a150b1aa-1605-4dc9-a9cc-73a343d3b198</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = '无原因' or . = '无原因')]</value>
      <webElementGuid>9187a2d5-db2f-44f8-b62e-e05940f59b32</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
