<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>noReason_PROD</name>
   <tag></tag>
   <elementGuidId>4271b75c-539a-4f10-8a07-913015410ec1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.ant-select-dropdown-menu-item-active.ant-select-dropdown-menu-item</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[15]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>730c7ba1-6bee-481e-9add-c031d9aeb41a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>unselectable</value>
      <webElementGuid>4007ec98-838e-49a0-a89b-92b5c18f92fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-select-dropdown-menu-item-active ant-select-dropdown-menu-item</value>
      <webElementGuid>9eb3bc7b-88af-4fc0-80ba-90bf106d3b88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>d55432fe-21ef-4528-bde6-67092ca69118</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>05df6f53-6712-4eec-8e01-332a03c6644f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>无原因</value>
      <webElementGuid>0100a6c8-237a-4216-a8b5-fec3401a45ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[4]/div[1]/div[@class=&quot;ant-select-dropdown ant-select-dropdown--single ant-select-dropdown-placement-bottomLeft&quot;]/div[1]/ul[@class=&quot;ant-select-dropdown-menu ant-select-dropdown-menu-vertical  ant-select-dropdown-menu-root&quot;]/li[@class=&quot;ant-select-dropdown-menu-item-active ant-select-dropdown-menu-item&quot;]</value>
      <webElementGuid>8015e693-1f2c-4c46-b341-fc74bc7535d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[15]</value>
      <webElementGuid>3300ac5f-dde5-4265-8461-17ab1c5175c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = '无原因' or . = '无原因')]</value>
      <webElementGuid>193c2299-f07d-4cca-a354-42ed8674cc2d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
