<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>note</name>
   <tag></tag>
   <elementGuidId>5eeebf3d-df82-48d9-a84d-bb34736d609e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#remark</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='remark']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>09af53fc-772e-4304-8d14-ff4b3531d540</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>1ccdc495-19d9-4936-9868-0a47b60b9d14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>remark</value>
      <webElementGuid>1fa09e3d-2393-4b5d-8a96-96cf9bdffb65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-__meta</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>6bf6f9c5-97ad-49f7-8df8-f2539121f2aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>be371a88-8980-4d29-b453-10cd2e86428d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input</value>
      <webElementGuid>e6ca7a9b-5c4c-4193-9a98-a611d0afc496</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;remark&quot;)</value>
      <webElementGuid>03e94b7a-5689-44c2-b214-f115d21b05e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='remark']</value>
      <webElementGuid>22750bd0-07ca-420d-b31e-a2f866a7d278</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span/textarea</value>
      <webElementGuid>8a8490fb-7d0f-4f71-9481-e7fa24172567</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@type = 'textarea' and @id = 'remark']</value>
      <webElementGuid>0f8a9609-fae5-416f-b598-1151dff74e5a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
