<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>search</name>
   <tag></tag>
   <elementGuidId>20fcf626-47d3-4db3-9f9b-f4a48916c2d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.anticon.anticon-search</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div/div[2]/div[2]/div/div/div/div/div[2]/span/div/button/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>eae1fa79-596e-4dd1-9370-3cab85ff09cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>anticon anticon-search</value>
      <webElementGuid>0c480e2e-f1bf-4c78-b0a6-71416d5f99aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;gx-layout&quot;]/div[@class=&quot;gx-layout-main&quot;]/div[@class=&quot;gx-layout-container&quot;]/div[@class=&quot;gx-layout-content&quot;]/div[1]/div[@class=&quot;ant-row gx-table-toolbar&quot;]/div[1]/div[@class=&quot;pull-left&quot;]/span[@class=&quot;ant-input-group ant-search-input&quot;]/div[@class=&quot;ant-input-group-wrap&quot;]/button[@class=&quot;ant-btn ant-search-btn ant-search-btn-noempty&quot;]/i[@class=&quot;anticon anticon-search&quot;]</value>
      <webElementGuid>15860816-b78a-46d5-978e-f8cf321a5924</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/div[2]/div[2]/div/div/div/div/div[2]/span/div/button/i</value>
      <webElementGuid>5e60d46d-8fb9-4b40-b1b2-653d1b54ab54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/i</value>
      <webElementGuid>c9dde1ee-d12f-48d9-998b-9e82290d122e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
